name: Build and deploy Python app to Azure Web App - RealTimeEmotionDetector

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r flask-server/requirements.txt

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Upload files via FTPS to Azure
        run: |
          curl -T "release.zip" --ftp-ssl ftps://$FTPS_SERVER/site/wwwroot/ --user $FTP_USERNAME:$FTP_PASSWORD
        env:
          FTPS_SERVER: ${{ secrets.AZURE_FTPS_ENDPOINT }}
          FTP_USERNAME: ${{ secrets.AZURE_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.AZURE_FTP_PASSWORD }}
